name = "NamedRowArrays"
uuid = "24b07f33-2be9-49a8-8558-3b162e5e4048"
authors = ["Lucas Valenzuela"]
version = "0.1.5"

[deps]
InvertedIndices = "41ab1584-1d38-5bbf-9106-f11c6c58b48f"

[compat]
julia = "1.9"
